### ISSUE TITLE
Transactions support for ReliableQueue

### ISSUE THREAD

**Issue by ThiemeNL** [loekd/ServiceFabric.Mocks#10]
Thanks for this very nice library!

I'm writing a unit test which uses the MockReliableQueue. I expect that the message is still in the queue once the CommitAsync on the transaction is **not** called. But the message is removed.

Are there any plans to support transactions?

```C#
var queue = await StateManager.GetOrAddAsync<IReliableQueue<Message>>("QueueName");
using (var tx = StateManager.CreateTransaction())
{
   var res = await queue.TryDequeueAsync(tx);    
   throw new Exception("Something went wrong");
   // Remove from queue
   await tx.CommitAsync();
}
```

**Comment by loekd** [comment]
Thank you for your feedback! 

It's quite challenging to build this. How would you do this?
If I think about it now, I'd try to add a private queue inside the MockReliableQueue and add Action delegates to it that hold the write operations, instead of performing the operations directly. And then, process the delegates when the transaction is committed. The downside is that you won't see your own writes during the transaction.

**Comment by ThiemeNL** [comment]
It is indeed quite a challenge! I'm thinking of something like a mirror queue, which becomes active once the commit is called. So indeed a private queue ect. If and when I have something working, I'll send a pull request.

**Comment by loekd** [comment]
This project was released recently. Perhaps it will help.
https://github.com/aelij/service-fabric-test-collections
