### ISSUE TITLE
Please support Service Fabric 8.0.521

### ISSUE THREAD

**Issue by danrozenberg** [loekd/ServiceFabric.Mocks#117]
It seems like `ServiceFabric.Mocks` Version `5.0.1` relies on SF version 8.0.516. Will we be getting an updated version of `ServiceFabric.Mocks` that support the latest SF?

Thank you in advance.

**Comment by tommarkosi** [comment]
we've been getting around it by "force" using direct NuGet references:

```
<!-- Needed until ServiceFabric.Mocks uses 8.0.521 -->
<PackageReference Include="Microsoft.ServiceFabric" Version="8.0.521" />
<PackageReference Include="Microsoft.ServiceFabric.Actors" Version="5.0.521" />
<PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" Version="5.0.521" />
<PackageReference Include="Microsoft.ServiceFabric.FabricTransport.Internal" Version="5.0.521" />
<PackageReference Include="Microsoft.ServiceFabric.Services" Version="5.0.521" />
<PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="5.0.521" />
<PackageReference Include="ServiceFabric.Mocks" Version="5.0.1" />
```
🤞 there are no breaking changes, lol

**Comment by loekd** [comment]
Hi @danrozenberg  and @tommarkosi ,
I've released a [new version](https://www.nuget.org/packages/ServiceFabric.Mocks/5.0.2) with support for the latest SF packages. For the future, please consider making a PR instead of an issue:

- Upgrade the package version with a minor tick if there are no breaking changes, by changing the <VersionPrefix>X.Y.Z</VersionPrefix> in the csproj file
- Add a line to the readme.md, stating the changes, e.g. 'upgraded to SF version x.y.z'.

Doing so will allow me to simply accept the PR, which will automatically trigger the release of a new package.
